# Generated by Django 2.2.4 on 2021-05-17 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_forms', '0002_hobbie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbie',
            name='tipo',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Debe Elegir un tipo'), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
