# Generated by Django 2.2.4 on 2021-05-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_forms', '0004_auto_20210518_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbie',
            name='name',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
